workflows:
  ios-workflow:
    name: CipkoTest iOS
    max_build_duration: 60
    integrations:
      app_store_connect: Codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.cipkotest.app
      vars:
        XCODE_PROJECT: "CipkoTest.xcodeproj"
        XCODE_SCHEME: "CipkoTest"
        BUNDLE_ID: "com.cipkotest.app"
        APP_STORE_APPLE_ID: "6761487757"
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen
      - name: Generate Xcode Project
        script: |
          xcodegen generate
      - name: Set up code signing settings
        script: |
          xcode-project use-profiles
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
